trigger:
- master

pool:
  name: azure-first project

steps:
- script: |
    # Download and install Apache Tomcat 9
    wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.95/bin/apache-tomcat-9.0.95.tar.gz
    sudo tar -xzf apache-tomcat-9.0.95.tar.gz -C /opt/
    sudo mv /opt/apache-tomcat-9.0.95 /opt/tomcat
    sudo chmod +x /opt/tomcat/bin/*.sh
    sudo sh /opt/tomcat/bin/startup.sh
  displayName: 'Install Apache Tomcat 9'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Build Project with Maven'

# Step 3: Run Tests
- script: |
    echo "Running Tests..."
    mvn test  # Run tests using Maven
  displayName: 'Run Tests'

# Step 4: Deploy the WAR file to Tomcat
- script: |
    echo "Deploying WAR to Tomcat..."
    # Deploy the WAR file to Tomcat
    sudo cp target/*.war /opt/tomcat/webapps/
    sudo /opt/tomcat/bin/shutdown.sh
    sudo /opt/tomcat/bin/startup.sh
  displayName: 'Deploy WAR to Tomcat'

# Optional: Step 5: Cleanup
- script: |
    echo "Cleaning up..."
    sudo rm -rf /opt/tomcat/webapps/*.war  # Remove old WAR files if necessary
  displayName: 'Cleanup Old WAR Files'

